.Dd $Mdocdate: November 6 2023 $
.Dt HYPRMAG 1
.Os Linux
.Sh NAME
.Nm hyprmag
.Nd wlroots-compatible wayland screen magnifier
.Sh SYNOPSIS
.Nm
.Op Fl rh
.Sh DESCRIPTION
The
.Nm
utility is a screen magnifier.
When
.Nm
is invoked the cursor is transformed into a magnifying lens.
.Pp
The options are as follows:
.It Fl h , Fl Fl help
Display a help message and exit successfully from the program.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr hyprpicker 1 ,
.Xr hyprctl 1 ,
.Xr hyprland 1 ,
.Xr sed 1 ,
.Xr wl-copy 1
.Pp
.Lk https://github.com/SIMULATAN/hyprmag "The Hyprmag Sources"
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was originally written by
.An Vaxerski Aq Lk https://github.com/vaxerski ,
transformed into a magnifying utility by
.An SIMULATAN Aq Lk https://github.com/SIMULATAN
and the manual page was made by
.An Thomas Voss Aq Mt mail@thomasvoss.com .
.Sh BUGS
.Lk https://github.com/SIMULATAN/hyprmag/issues "The Hyprmag Bug Tracker"
